# Generated by Django 2.2.1 on 2019-12-06 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, default=None, max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('destination_code', models.CharField(max_length=3)),
                ('source_code', models.CharField(max_length=3)),
                ('arr_time', models.TimeField()),
                ('dept_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flight', to='holidays.Flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crno', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('expdate', models.DateField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=150)),
                ('country_name1', models.CharField(default='India', max_length=150)),
                ('name2', models.CharField(blank=True, max_length=150)),
                ('country_name2', models.CharField(blank=True, default='India', max_length=150)),
                ('name3', models.CharField(blank=True, max_length=150)),
                ('country_name3', models.CharField(blank=True, default='India', max_length=150)),
                ('package', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('place', models.ForeignKey(on_delete='models.CASCADE', related_name='images', to='holidays.Place')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.BooleanField(default=False)),
                ('number', models.IntegerField(default=1)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holidays.Place')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('packages', models.ManyToManyField(to='holidays.BookingPlace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('row_no', models.CharField(default=None, max_length=1)),
                ('seat_no', models.IntegerField()),
                ('booked', models.BooleanField(default=False)),
                ('flightbooking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flight_booking', to='holidays.FlightBooking')),
            ],
            options={
                'unique_together': {('seat_no', 'row_no')},
            },
        ),
    ]
