# Generated by Django 2.2.1 on 2019-12-12 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_auto_20191206_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AlterField(
            model_name='bookingplace',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='holidays.Place'),
        ),
    ]
